/**
 * 组件库统一导出入口
 * 集中导出所有公共组件供外部引用
 */
export { default as PaywallPopup } from './PaywallPopup'
export { default as PrivacyPopup } from './PrivacyPopup'
export { default as PetCard } from './PetCard'
export { default as PetSwitcher } from './PetSwitcher'
export { default as PetDeceasedModal } from './PetDeceasedModal'
export { default as VaccineCalendar } from './VaccineCalendar'
export { default as VaccineAddModal } from './VaccineAddModal'
export { default as VaccineRecordCard } from './VaccineRecordCard'
export { default as PageLoading } from './PageLoading'
export { default as PageError } from './PageError'
export { default as PetAvatar } from './PetAvatar'
export { default as AchievementCard } from './AchievementCard'
export { ACHIEVEMENT_DEFS } from './AchievementCard'
export type { AchievementConfig } from './AchievementCard'
export { default as FoodShareCard } from './FoodShareCard'
export { default as HealthTrendShareCard } from './HealthTrendShareCard'
export { default as VaccineShareCard } from './VaccineShareCard'
export { default as NpsSurvey } from './NpsSurvey'
export { default as AccountDeletionConfirm } from './AccountDeletionConfirm'
export { default as EmotionResponseCard } from './EmotionResponseCard'
export { default as GriefCompanion } from './GriefCompanion'
export { default as AchievementShareCard } from './AchievementShareCard'
export { default as CrisisReferralCard } from './CrisisReferralCard'
export { default as EmergencyAlert } from './EmergencyAlert'
export { default as HealthReportPreview } from './HealthReportPreview'
export { default as AnomalyMarker } from './AnomalyMarker'
export { default as CarePlanCard } from './CarePlanCard'
export { default as EmptyStateGuide } from './EmptyStateGuide'
export { default as NewbieTaskCard } from './NewbieTaskCard'
export { default as RecommendContentCard } from './RecommendContentCard'
export { default as Icon } from './Icon'
export type { IconName, LineIconName, FillIconName } from './Icon'
export { default as Illustration } from './Illustration'
export { default as EmptyState } from './EmptyState'
export { default as PageHero } from './PageHero'
export type { IllustrationName } from '../data/illustrations'
export { illustrationUrl, ILLUSTRATION_NAMES } from '../data/illustrations'
export { default as PageBackground } from './PageBackground'
export { default as BackgroundPicker } from './BackgroundPicker'
export { emojiToIcon, shouldReplaceEmoji, EMOJI_TO_ICON, KEEP_EMOJI } from './emojiIconMap'
